### ISSUE TITLE
Tính năng nhận diện chữ viết tay

### ISSUE THREAD

**Issue by NguyenDung0210** [Team-28-Software-Engineering/SmartNoteAI#22]
Cho phép người dùng chụp ảnh hoặc dán văn bản viết tay vào và cung cấp chuyển đổi hình ảnh đó thành văn bản máy tính, trường hợp văn bản là dạng chữ ký thì phần mềm sẽ chuyển đổi thành dạng scan và đồng thời hỏi người dùng việc lưu chữ ký đó dạng digital.

**Comment by hoangbuituananh132109** [comment]
hiện tại đây là phần AI duy nhất trong dự án của chúng ta, tôi dự định cho nó hoạt động theo cách thêm tính năng này vào phần "File" và khi mở nó thì sẽ mở ra 1 cửa sổ mới cho phép đưa ảnh vào và chúng ta sẽ lấy code nhận diện ảnh từ đâu đó về để tạo phần này
